version: '3.8'

services:

  backend:
    build:
      context: .                        # Le contexte est tout le projet
      dockerfile: backend/Dockerfile     # Dockerfile spécifique pour le backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    networks:
      - flix_network

  frontend:
    build:
      context: ./frontend               # Le contexte est uniquement le dossier frontend
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    environment:
      - BACKEND_URL=http://backend:8000  # <<< On injecte ici l'adresse du backend pour le frontend
    depends_on:
      - backend                         # Le frontend attend que le backend démarre
    networks:
      - flix_network

networks:
  flix_network:
    driver: bridge
